"""System resource monitoring and cycle-to-cycle resource leak detection.

Exposes low-overhead, bounded process and host metrics (CPU, RSS, VMS, threads,
asyncio tasks, file descriptors, GC stats, disk capacity) with cross-platform
support for Windows and Linux. Tracks resource baselines across ingestion cycles
to detect sustained monotonic memory leaks without false alarms on temporary peaks.
"""

from __future__ import annotations

import asyncio
import ctypes
import gc
import logging
import shutil
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ingestion.monitoring.metrics import REGISTRY

logger = logging.getLogger(__name__)

# Register Prometheus metrics
COMPONENT_CPU_PERCENT = REGISTRY.gauge(
    "weather_component_cpu_percent",
    "Component process CPU utilization percentage (0-100+)",
    labelnames=("component",),
)
COMPONENT_MEMORY_RSS_BYTES = REGISTRY.gauge(
    "weather_component_memory_rss_bytes",
    "Component process resident memory size (RSS) in bytes",
    labelnames=("component",),
)
PROCESS_CPU_PERCENT = REGISTRY.gauge(
    "weather_process_cpu_percent",
    "Current process CPU utilization percentage (0-100+)",
)
SYSTEM_CPU_PERCENT = REGISTRY.gauge(
    "weather_system_cpu_percent",
    "Host system overall CPU utilization percentage (0-100)",
)
PROCESS_MEMORY_RSS_BYTES = REGISTRY.gauge(
    "weather_process_memory_rss_bytes",
    "Process resident set size (RSS) in bytes",
)
PROCESS_MEMORY_VMS_BYTES = REGISTRY.gauge(
    "weather_process_memory_vms_bytes",
    "Process virtual memory size (VMS) in bytes",
)
PROCESS_MEMORY_PEAK_RSS_BYTES = REGISTRY.gauge(
    "weather_process_memory_peak_rss_bytes",
    "Peak process resident set size in bytes",
)
SYSTEM_MEMORY_TOTAL_BYTES = REGISTRY.gauge(
    "weather_system_memory_total_bytes",
    "Host system total physical memory in bytes",
)
SYSTEM_MEMORY_USED_BYTES = REGISTRY.gauge(
    "weather_system_memory_used_bytes",
    "Host system used physical memory in bytes",
)
SYSTEM_MEMORY_FREE_BYTES = REGISTRY.gauge(
    "weather_system_memory_free_bytes",
    "Host system available/free physical memory in bytes",
)
SYSTEM_MEMORY_USED_PERCENT = REGISTRY.gauge(
    "weather_system_memory_used_percent",
    "Host system memory utilization percentage (0-100)",
)
PROCESS_ACTIVE_THREADS = REGISTRY.gauge(
    "weather_process_active_threads",
    "Number of active Python threads",
)
PROCESS_ASYNCIO_TASKS = REGISTRY.gauge(
    "weather_process_asyncio_tasks",
    "Number of active asyncio tasks in current running event loop",
)
PROCESS_OPEN_FDS = REGISTRY.gauge(
    "weather_process_open_file_descriptors",
    "Number of open file descriptors / handles",
)
DISK_TOTAL_BYTES = REGISTRY.gauge(
    "weather_disk_total_bytes",
    "Total disk capacity in bytes",
    labelnames=("path",),
)
DISK_USED_BYTES = REGISTRY.gauge(
    "weather_disk_used_bytes",
    "Used disk space in bytes",
    labelnames=("path",),
)
DISK_FREE_BYTES = REGISTRY.gauge(
    "weather_disk_free_bytes",
    "Free disk space in bytes",
    labelnames=("path",),
)
DISK_USED_PERCENT = REGISTRY.gauge(
    "weather_disk_used_percent",
    "Disk utilization percentage (0-100)",
    labelnames=("path",),
)
STAGING_DOWNLOADS_BYTES = REGISTRY.gauge(
    "weather_staging_downloads_bytes",
    "Temporary download staging directory total disk usage in bytes",
)
MEMORY_LEAK_WARNING = REGISTRY.gauge(
    "weather_memory_leak_warning",
    "Memory leak indicator (1 if sustained post-cycle growth detected, 0 otherwise)",
)


@dataclass(frozen=True)
class MemoryInfo:
    """Process memory statistics."""

    rss_bytes: int
    vms_bytes: int
    peak_rss_bytes: int


@dataclass(frozen=True)
class SystemMemoryInfo:
    """Host system physical memory statistics."""

    total_bytes: int
    used_bytes: int
    free_bytes: int
    used_percent: float


@dataclass(frozen=True)
class DiskInfo:
    """Disk space capacity and utilization."""

    path: str
    total_bytes: int
    used_bytes: int
    free_bytes: int
    used_percent: float

    @property
    def is_warning(self) -> bool:
        return self.used_percent >= 80.0

    @property
    def is_critical(self) -> bool:
        return self.used_percent >= 90.0


@dataclass(frozen=True)
class CycleResourceSnapshot:
    """Resource snapshot captured for a specific cycle."""

    cycle_key: str
    pre_baseline_rss: int
    peak_rss: int
    post_baseline_rss: int
    timestamp: float
    threads: int


@dataclass
class ResourceLeakReport:
    """Report generated by the cycle leak detector."""

    is_leak: bool
    retained_growth_bytes: int
    retained_growth_pct: float
    cycle_count: int
    message: str


class SystemResourceCollector:
    """Thread-safe collector for CPU, memory, thread, task, and disk metrics."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._last_cpu_time: float | None = None
        self._last_monotonic: float | None = None
        self._last_psutil_cpu_times: Any = None
        self._last_sys_cpu_total: float | None = None
        self._last_sys_cpu_idle: float | None = None
        self._peak_rss: int = 0
        self._is_windows = sys.platform == "win32"
        self._init_platform()

    def _init_platform(self) -> None:
        if self._is_windows:
            try:
                from ctypes import wintypes

                class PROCESS_MEMORY_COUNTERS(ctypes.Structure):
                    _fields_ = [
                        ("cb", wintypes.DWORD),
                        ("PageFaultCount", wintypes.DWORD),
                        ("PeakWorkingSetSize", ctypes.c_size_t),
                        ("WorkingSetSize", ctypes.c_size_t),
                        ("QuotaPeakPagedPoolUsage", ctypes.c_size_t),
                        ("QuotaPagedPoolUsage", ctypes.c_size_t),
                        ("QuotaPeakNonPagedPoolUsage", ctypes.c_size_t),
                        ("QuotaNonPagedPoolUsage", ctypes.c_size_t),
                        ("PagefileUsage", ctypes.c_size_t),
                        ("PeakPagefileUsage", ctypes.c_size_t),
                    ]

                class MEMORYSTATUSEX(ctypes.Structure):
                    _fields_ = [
                        ("dwLength", wintypes.DWORD),
                        ("dwMemoryLoad", wintypes.DWORD),
                        ("ullTotalPhys", ctypes.c_uint64),
                        ("ullAvailPhys", ctypes.c_uint64),
                        ("ullTotalPageFile", ctypes.c_uint64),
                        ("ullAvailPageFile", ctypes.c_uint64),
                        ("ullTotalVirtual", ctypes.c_uint64),
                        ("ullAvailVirtual", ctypes.c_uint64),
                        ("ullAvailExtendedVirtual", ctypes.c_uint64),
                    ]

                self._pmc_cls = PROCESS_MEMORY_COUNTERS
                self._msex_cls = MEMORYSTATUSEX
                win_dll = getattr(ctypes, "windll", None)
                if win_dll is not None:
                    psapi = win_dll.psapi
                    psapi.GetProcessMemoryInfo.argtypes = [
                        wintypes.HANDLE,
                        ctypes.POINTER(PROCESS_MEMORY_COUNTERS),
                        wintypes.DWORD,
                    ]
                    psapi.GetProcessMemoryInfo.restype = wintypes.BOOL
                    self._psapi = psapi
                    self._kernel32 = win_dll.kernel32
                    self._kernel32.GlobalMemoryStatusEx.argtypes = [
                        ctypes.POINTER(MEMORYSTATUSEX),
                    ]
                    self._kernel32.GlobalMemoryStatusEx.restype = wintypes.BOOL
                    self._has_win_api = True
                else:
                    self._has_win_api = False
            except Exception as exc:  # noqa: BLE001
                logger.debug("Windows psapi initialization failed: %s", exc)
                self._has_win_api = False
        else:
            self._has_win_api = False

    def get_memory_info(self) -> MemoryInfo:
        """Return current RSS, VMS, and peak RSS bytes."""
        rss = 0
        vms = 0
        peak = 0

        # Optional psutil fast path if installed
        try:
            import psutil  # type: ignore[import-untyped]

            proc = psutil.Process()
            mem = proc.memory_info()
            rss = int(mem.rss)
            vms = int(mem.vms)
        except Exception:  # noqa: BLE001
            # Windows native implementation
            if self._is_windows and self._has_win_api:
                try:
                    counters = self._pmc_cls()
                    counters.cb = ctypes.sizeof(self._pmc_cls)
                    handle = self._kernel32.GetCurrentProcess()
                    if self._psapi.GetProcessMemoryInfo(
                        handle, ctypes.byref(counters), counters.cb
                    ):
                        rss = int(counters.WorkingSetSize)
                        vms = int(counters.PagefileUsage)
                        peak = int(counters.PeakWorkingSetSize)
                except Exception as exc:  # noqa: BLE001
                    logger.debug("Windows GetProcessMemoryInfo failed: %s", exc)

            # Linux native implementation via /proc/self/status and resource
            if not self._is_windows and rss == 0:
                try:
                    import resource

                    getrusage_fn = getattr(resource, "getrusage", None)
                    rusage_self = getattr(resource, "RUSAGE_SELF", 0)
                    if getrusage_fn is not None:
                        rusage = getrusage_fn(rusage_self)
                        # maxrss is in kilobytes on Linux, bytes on Darwin/BSD
                        scale = 1024 if sys.platform.startswith("linux") else 1
                        peak = int(rusage.ru_maxrss * scale)

                    # Read current RSS and VMS from /proc/self/status
                    proc_status = Path("/proc/self/status")
                    if proc_status.is_file():
                        for line in proc_status.read_text().splitlines():
                            if line.startswith("VmRSS:"):
                                parts = line.split()
                                if len(parts) >= 2 and parts[1].isdigit():
                                    rss = int(parts[1]) * 1024
                            elif line.startswith("VmSize:"):
                                parts = line.split()
                                if len(parts) >= 2 and parts[1].isdigit():
                                    vms = int(parts[1]) * 1024
                    if rss == 0:
                        rss = peak
                except Exception as exc:  # noqa: BLE001
                    logger.debug("Linux memory read failed: %s", exc)

        with self._lock:
            if rss > self._peak_rss:
                self._peak_rss = rss
            if peak > self._peak_rss:
                self._peak_rss = peak
            peak_val = self._peak_rss

        return MemoryInfo(rss_bytes=rss, vms_bytes=vms, peak_rss_bytes=peak_val)

    def get_cpu_percent(self) -> float:
        """Calculate process CPU % since previous invocation (non-blocking)."""
        now_mono = time.monotonic()
        try:
            # Process times (user + system)
            cpu_times = time.process_time()
        except Exception:
            return 0.0

        with self._lock:
            if self._last_cpu_time is None or self._last_monotonic is None:
                self._last_cpu_time = cpu_times
                self._last_monotonic = now_mono
                return 0.0

            dt_mono = now_mono - self._last_monotonic
            dt_cpu = cpu_times - self._last_cpu_time

            self._last_cpu_time = cpu_times
            self._last_monotonic = now_mono

            if dt_mono <= 0:
                return 0.0

            # Percentage across all cores
            pct = (dt_cpu / dt_mono) * 100.0
            return max(0.0, round(pct, 2))

    def get_system_cpu_percent(self) -> float:
        """Return overall system CPU utilization percentage (0-100).

        Cross-platform across Windows, Linux x86_64, and Linux aarch64/ARM64.
        Uses psutil fast path if available; falls back to Linux /proc/stat or
        process-level CPU to maintain fail-open reliability.
        """
        # 1. Preferred path: psutil (cross-platform, x86_64 & aarch64)
        try:
            import psutil  # type: ignore[import-untyped]

            c_times = psutil.cpu_times()
            with self._lock:
                if self._last_psutil_cpu_times is not None:
                    d_idle = c_times.idle - self._last_psutil_cpu_times.idle
                    d_total = sum(c_times) - sum(self._last_psutil_cpu_times)
                    self._last_psutil_cpu_times = c_times
                    if d_total > 0:
                        pct = (1.0 - (d_idle / d_total)) * 100.0
                        return max(0.0, min(100.0, round(float(pct), 2)))
                else:
                    self._last_psutil_cpu_times = c_times
                    return 0.0
        except Exception:  # noqa: BLE001
            pass

        # 2. Linux kernel fallback (/proc/stat - identical on x86_64 and aarch64)
        if not self._is_windows:
            try:
                stat_path = Path("/proc/stat")
                if stat_path.is_file():
                    first_line = stat_path.read_text().splitlines()[0]
                    fields = [float(x) for x in first_line.split()[1:]]
                    idle_time = fields[3] + (fields[4] if len(fields) > 4 else 0.0)
                    total_time = sum(fields)
                    with self._lock:
                        if (
                            self._last_sys_cpu_total is not None
                            and self._last_sys_cpu_idle is not None
                        ):
                            d_total = total_time - self._last_sys_cpu_total
                            d_idle = idle_time - self._last_sys_cpu_idle
                            self._last_sys_cpu_total = total_time
                            self._last_sys_cpu_idle = idle_time
                            if d_total > 0:
                                pct = ((d_total - d_idle) / d_total) * 100.0
                                return max(0.0, min(100.0, round(pct, 2)))
                        else:
                            self._last_sys_cpu_total = total_time
                            self._last_sys_cpu_idle = idle_time
                            return 0.0
            except Exception as exc:  # noqa: BLE001
                logger.debug("Linux /proc/stat CPU read failed: %s", exc)

        # 3. Final fallback: process CPU percentage
        return self.get_cpu_percent()

    def get_system_memory_info(self) -> SystemMemoryInfo:
        """Return host system physical memory statistics.

        Cross-platform across Windows, Linux x86_64, and Linux aarch64/ARM64.
        Uses psutil fast path if available; falls back to Linux /proc/meminfo or
        Windows GlobalMemoryStatusEx to maintain fail-open reliability.
        """
        # 1. Preferred path: psutil (cross-platform, x86_64 & aarch64)
        try:
            import psutil  # type: ignore[import-untyped]

            v = psutil.virtual_memory()
            return SystemMemoryInfo(
                total_bytes=int(v.total),
                used_bytes=int(v.used),
                free_bytes=int(v.available),
                used_percent=round(float(v.percent), 2),
            )
        except Exception:  # noqa: BLE001
            pass

        # 2. Linux kernel fallback (/proc/meminfo - identical on x86_64 and aarch64)
        if not self._is_windows:
            try:
                meminfo_path = Path("/proc/meminfo")
                if meminfo_path.is_file():
                    data: dict[str, int] = {}
                    for line in meminfo_path.read_text().splitlines():
                        parts = line.split(":")
                        if len(parts) == 2:
                            key = parts[0].strip()
                            val_str = parts[1].strip().split()[0]
                            if val_str.isdigit():
                                data[key] = int(val_str) * 1024
                    total = data.get("MemTotal", 0)
                    avail = data.get("MemAvailable", data.get("MemFree", 0))
                    used = max(0, total - avail)
                    pct = (used / total * 100.0) if total > 0 else 0.0
                    return SystemMemoryInfo(
                        total_bytes=total,
                        used_bytes=used,
                        free_bytes=avail,
                        used_percent=round(pct, 2),
                    )
            except Exception as exc:  # noqa: BLE001
                logger.debug("Linux /proc/meminfo read failed: %s", exc)

        # 3. Windows native API fallback (GlobalMemoryStatusEx)
        if self._is_windows and self._has_win_api:
            try:
                stat = self._msex_cls()
                stat.dwLength = ctypes.sizeof(self._msex_cls)
                if self._kernel32.GlobalMemoryStatusEx(ctypes.byref(stat)):
                    total = int(stat.ullTotalPhys)
                    avail = int(stat.ullAvailPhys)
                    used = max(0, total - avail)
                    pct = float(stat.dwMemoryLoad)
                    return SystemMemoryInfo(
                        total_bytes=total,
                        used_bytes=used,
                        free_bytes=avail,
                        used_percent=round(pct, 2),
                    )
            except Exception as exc:  # noqa: BLE001
                logger.debug("Windows GlobalMemoryStatusEx failed: %s", exc)

        return SystemMemoryInfo(
            total_bytes=0,
            used_bytes=0,
            free_bytes=0,
            used_percent=0.0,
        )

    def get_thread_count(self) -> int:
        """Return number of active Python threads."""
        return threading.active_count()

    def get_asyncio_task_count(self) -> int:
        """Return number of running asyncio tasks in the current loop, if active."""
        try:
            loop = asyncio.get_running_loop()
            if loop.is_running():
                return len(asyncio.all_tasks(loop))
        except RuntimeError:
            pass
        return 0

    def get_open_file_descriptors(self) -> int:
        """Return open file descriptors where available, or -1 if unsupported."""
        if not self._is_windows:
            try:
                fd_path = Path("/proc/self/fd")
                if fd_path.is_dir():
                    return len(list(fd_path.iterdir()))
            except Exception:  # noqa: BLE001
                pass
        return -1

    def get_gc_stats(self) -> dict[str, Any]:
        """Return Python garbage collection counts and thresholds."""
        return {
            "counts": gc.get_count(),
            "threshold": gc.get_threshold(),
            "stats": gc.get_stats() if hasattr(gc, "get_stats") else [],
        }

    def get_disk_usage(self, path: str | Path) -> DiskInfo:
        """Return capacity and utilization for a given path."""
        p = Path(path).resolve()
        # Find nearest existing directory
        target = p if p.exists() else p.parent
        while not target.exists() and target != target.parent:
            target = target.parent

        usage = shutil.disk_usage(str(target))
        total = usage.total
        used = usage.used
        free = usage.free
        pct = (used / total) * 100.0 if total > 0 else 0.0

        return DiskInfo(
            path=str(path),
            total_bytes=total,
            used_bytes=used,
            free_bytes=free,
            used_percent=round(pct, 2),
        )

    def sample_component_resources(self, component: str) -> tuple[float, int]:
        """Sample current process CPU % and RSS bytes, and record as component metrics."""
        cpu = self.get_cpu_percent()
        mem = self.get_memory_info()
        COMPONENT_CPU_PERCENT.labels(component=component).set(cpu)
        COMPONENT_MEMORY_RSS_BYTES.labels(component=component).set(float(mem.rss_bytes))
        return cpu, mem.rss_bytes

    def collect_and_export(
        self,
        disk_paths: tuple[str | Path, ...] = (".",),
    ) -> dict[str, Any]:
        """Collect all resource statistics, update Prometheus metrics, and return dict."""
        mem = self.get_memory_info()
        cpu = self.get_cpu_percent()
        sys_cpu = self.get_system_cpu_percent()
        sys_mem = self.get_system_memory_info()
        threads = self.get_thread_count()
        tasks = self.get_asyncio_task_count()
        fds = self.get_open_file_descriptors()

        # Component breakdown: exporter process itself
        COMPONENT_CPU_PERCENT.labels(component="exporter").set(cpu)
        COMPONENT_MEMORY_RSS_BYTES.labels(component="exporter").set(float(mem.rss_bytes))

        # Both system CPU and legacy process gauge are populated for compatibility
        SYSTEM_CPU_PERCENT.set(sys_cpu)
        PROCESS_CPU_PERCENT.set(sys_cpu)

        # Host system physical memory metrics
        SYSTEM_MEMORY_TOTAL_BYTES.set(float(sys_mem.total_bytes))
        SYSTEM_MEMORY_USED_BYTES.set(float(sys_mem.used_bytes))
        SYSTEM_MEMORY_FREE_BYTES.set(float(sys_mem.free_bytes))
        SYSTEM_MEMORY_USED_PERCENT.set(float(sys_mem.used_percent))

        # Process-level memory metrics
        PROCESS_MEMORY_RSS_BYTES.set(float(mem.rss_bytes))
        PROCESS_MEMORY_VMS_BYTES.set(float(mem.vms_bytes))
        PROCESS_MEMORY_PEAK_RSS_BYTES.set(float(mem.peak_rss_bytes))
        PROCESS_ACTIVE_THREADS.set(float(threads))
        PROCESS_ASYNCIO_TASKS.set(float(tasks))
        if fds >= 0:
            PROCESS_OPEN_FDS.set(float(fds))

        disks: list[DiskInfo] = []
        for dpath in disk_paths:
            try:
                dinfo = self.get_disk_usage(dpath)
                disks.append(dinfo)
                p_str = str(dpath)
                DISK_TOTAL_BYTES.labels(path=p_str).set(float(dinfo.total_bytes))
                DISK_USED_BYTES.labels(path=p_str).set(float(dinfo.used_bytes))
                DISK_FREE_BYTES.labels(path=p_str).set(float(dinfo.free_bytes))
                DISK_USED_PERCENT.labels(path=p_str).set(float(dinfo.used_percent))
            except Exception as exc:  # noqa: BLE001
                logger.debug("Failed disk usage collection for %s: %s", dpath, exc)

        # Temporary downloads staging disk usage
        staging_dir = Path("downloads")
        staging_bytes = 0
        if staging_dir.is_dir():
            try:
                staging_bytes = sum(
                    f.stat().st_size for f in staging_dir.rglob("*") if f.is_file()
                )
            except Exception:  # noqa: BLE001
                pass
        STAGING_DOWNLOADS_BYTES.set(float(staging_bytes))

        return {
            "cpu_percent": cpu,
            "system_cpu_percent": sys_cpu,
            "memory": mem,
            "system_memory": sys_mem,
            "threads": threads,
            "asyncio_tasks": tasks,
            "open_fds": fds,
            "disks": disks,
            "gc": self.get_gc_stats(),
        }


class CycleResourceLeakDetector:
    """Detects sustained memory and resource growth across multiple completed cycles.

    Distinguishes normal temporary high-memory execution peaks from true retained
    memory leaks by comparing the post-cycle resting baselines across N consecutive runs.
    """

    def __init__(
        self,
        history_len: int = 10,
        min_cycles: int = 5,
        min_growth_pct: float = 0.15,
        min_growth_bytes: int = 150 * 1024 * 1024,  # 150 MB
    ) -> None:
        self.history_len = max(5, history_len)
        self.min_cycles = min_cycles
        self.min_growth_pct = min_growth_pct
        self.min_growth_bytes = min_growth_bytes
        self._snapshots: list[CycleResourceSnapshot] = []
        self._lock = threading.Lock()

    def record_cycle(
        self,
        cycle_key: str,
        pre_baseline_rss: int,
        peak_rss: int,
        post_baseline_rss: int,
        threads: int = 0,
        timestamp: float | None = None,
    ) -> None:
        """Record a completed cycle's resource profile."""
        ts = time.time() if timestamp is None else timestamp
        snap = CycleResourceSnapshot(
            cycle_key=cycle_key,
            pre_baseline_rss=pre_baseline_rss,
            peak_rss=peak_rss,
            post_baseline_rss=post_baseline_rss,
            timestamp=ts,
            threads=threads,
        )
        with self._lock:
            self._snapshots.append(snap)
            if len(self._snapshots) > self.history_len:
                self._snapshots = self._snapshots[-self.history_len :]

    def evaluate_leak(self) -> ResourceLeakReport:
        """Evaluate whether sustained monotonic memory leak is occurring."""
        with self._lock:
            snaps = list(self._snapshots)

        if len(snaps) < self.min_cycles:
            return ResourceLeakReport(
                is_leak=False,
                retained_growth_bytes=0,
                retained_growth_pct=0.0,
                cycle_count=len(snaps),
                message=f"Insufficient cycle history ({len(snaps)}/{self.min_cycles})",
            )

        # Examine the most recent N cycles
        recent = snaps[-self.min_cycles :]
        post_values = [s.post_baseline_rss for s in recent]

        # Check monotonic non-decreasing trend
        is_strictly_growing = True
        for i in range(len(post_values) - 1):
            # Allow minor noise margin of 1%
            if post_values[i + 1] < post_values[i] * 0.99:
                is_strictly_growing = False
                break

        first_val = post_values[0]
        last_val = post_values[-1]
        growth_bytes = last_val - first_val
        growth_pct = (growth_bytes / first_val) if first_val > 0 else 0.0

        is_leak = (
            is_strictly_growing
            and growth_bytes >= self.min_growth_bytes
            and growth_pct >= self.min_growth_pct
        )

        MEMORY_LEAK_WARNING.set(1.0 if is_leak else 0.0)

        if is_leak:
            msg = (
                f"Sustained baseline memory leak detected over {len(recent)} cycles: "
                f"+{growth_bytes / (1024 * 1024):.1f} MB ({growth_pct * 100:.1f}%) "
                f"from {recent[0].cycle_key} to {recent[-1].cycle_key}"
            )
        else:
            msg = (
                f"Memory baseline stable over {len(recent)} cycles "
                f"(net change: {growth_bytes / (1024 * 1024):+.1f} MB, {growth_pct * 100:+.1f}%)"
            )

        return ResourceLeakReport(
            is_leak=is_leak,
            retained_growth_bytes=growth_bytes,
            retained_growth_pct=round(growth_pct, 4),
            cycle_count=len(recent),
            message=msg,
        )

    def get_recent_history(self) -> list[CycleResourceSnapshot]:
        with self._lock:
            return list(self._snapshots)


#: Global collector and leak detector singletons
RESOURCE_COLLECTOR = SystemResourceCollector()
LEAK_DETECTOR = CycleResourceLeakDetector()
