"""Strict parser and product-aware record selector for NOAA NOMADS .idx files.

NOMADS serves a ``.idx`` file alongside every operational GFS and GEFS GRIB2
product. These index files are generated by ``wgrib2`` with standard 1-based
message lines:

    <record_num>:<byte_offset>:d=<cycle>:<parameter>:<level>:<forecast_step>[:<extra>]

This module provides:
1. :class:`IdxRecord` — an immutable representation of one GRIB2 record boundary
   and its descriptive metadata.
2. :func:`parse_idx` — a strict parser enforcing sequential record numbers,
   monotonically increasing byte offsets, and non-empty metadata.
3. :func:`select_records` — product-aware record selection that resolves
   platform-required variables (e.g. ``temperature_2m``, ``precipitation_rate``)
   to exact GRIB message byte boundaries for GFS and GEFS.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from ingestion.core.base import IngestionError


class IdxParseError(IngestionError):
    """Raised when a NOMADS .idx file cannot be parsed or violates invariants."""


class SelectionStatus(str, Enum):
    """Classification of a variable selection outcome."""

    SELECTED = "selected"
    UNSUPPORTED = "unsupported"
    REQUIRED_BUT_MISSING = "required_but_missing"
    AMBIGUOUS = "ambiguous"


@dataclass(frozen=True, slots=True)
class IdxRecord:
    """An immutable description of a single GRIB2 message within a remote file.

    Attributes:
        record_number: 1-based sequence index in the GRIB2 file.
        start_offset: Absolute start byte offset in the remote GRIB2 file.
        end_offset: Inclusive end byte offset, or ``None`` for the final record
            when the total file size is not yet bounded.
        date_token: Reference cycle token (e.g. ``"d=2026082600"``).
        parameter: GRIB parameter mnemonic (e.g. ``"TMP"``, ``"PRATE"``).
        level_description: Vertical level string (e.g. ``"2 m above ground"``).
        forecast_description: Forecast step/type string (e.g. ``"6 hour fcst"``).
        ensemble_description: Optional ensemble metadata (e.g. ``"ENS=+1"``).
        raw_line: The exact original line from the ``.idx`` stream.
    """

    record_number: int
    start_offset: int
    end_offset: int | None
    date_token: str
    parameter: str
    level_description: str
    forecast_description: str
    ensemble_description: str
    raw_line: str

    @property
    def byte_length(self) -> int | None:
        """Return the exact byte span, or ``None`` if unbounded."""
        if self.end_offset is None:
            return None
        return self.end_offset - self.start_offset + 1


@dataclass(frozen=True)
class VariableSelection:
    """Selection outcome for a single canonical platform variable."""

    variable_code: str
    status: SelectionStatus
    record: IdxRecord | None = None
    matched_records: tuple[IdxRecord, ...] = ()


@dataclass(frozen=True)
class SelectionResult:
    """Aggregated selection outcome for all requested variables.

    Attributes:
        selected_records: Records to download, strictly sorted by ``start_offset``
            ascending to preserve original upstream GRIB message order.
        variable_selections: Map of variable code to its selection outcome.
        missing_required: List of required variables that were unexpectedly missing.
        unsupported: List of variables not supported by this product layout.
        ambiguous: List of variables that matched multiple conflicting records.
    """

    selected_records: tuple[IdxRecord, ...]
    variable_selections: dict[str, VariableSelection]
    missing_required: tuple[str, ...]
    unsupported: tuple[str, ...]
    ambiguous: tuple[str, ...]

    @property
    def is_valid(self) -> bool:
        """Return True if all required variables were unambiguously resolved."""
        return len(self.missing_required) == 0 and len(self.ambiguous) == 0


def parse_idx(text: str) -> list[IdxRecord]:
    r"""Parse raw NOMADS .idx text into a strictly validated list of IdxRecords.

    Enforces:
    * Non-empty text.
    * Each line has at least 6 colon-separated fields.
    * Record numbers are strictly sequential ($1, 2, 3, \dots, N$).
    * Byte offsets are non-negative, starting at 0, and strictly monotonically
      increasing without duplicates.
    * End offsets are derived as ``start_offset[i+1] - 1`` (and ``None`` for
      the final record).

    Args:
        text: Raw UTF-8 text of a NOMADS ``.idx`` file.

    Returns:
        List of parsed :class:`IdxRecord` instances.

    Raises:
        IdxParseError: If the index is empty, malformed, or violates offset
            monotonicity.
    """
    stripped = text.strip()
    if not stripped:
        raise IdxParseError("Empty or whitespace-only .idx content")

    lines = [line.strip() for line in stripped.splitlines() if line.strip()]
    if not lines:
        raise IdxParseError("No valid record lines found in .idx")

    raw_records: list[tuple[int, int, str, str, str, str, str, str]] = []
    prev_offset = -1

    for idx, line in enumerate(lines):
        parts = line.split(":")
        if len(parts) < 6:
            raise IdxParseError(
                f"Malformed .idx line {idx + 1}: expected at least 6 fields, "
                f"got {len(parts)}: {line!r}"
            )

        try:
            rec_num = int(parts[0])
        except ValueError as exc:
            raise IdxParseError(
                f"Invalid record number on line {idx + 1}: {parts[0]!r}"
            ) from exc

        expected_rec_num = idx + 1
        if rec_num != expected_rec_num:
            raise IdxParseError(
                f"Non-sequential record number on line {idx + 1}: "
                f"expected {expected_rec_num}, got {rec_num}"
            )

        try:
            start_offset = int(parts[1])
        except ValueError as exc:
            raise IdxParseError(
                f"Invalid byte offset on line {idx + 1}: {parts[1]!r}"
            ) from exc

        if start_offset < 0:
            raise IdxParseError(
                f"Negative byte offset on line {idx + 1}: {start_offset}"
            )

        if idx == 0 and start_offset != 0:
            raise IdxParseError(
                f"First record on line 1 must start at byte offset 0, got {start_offset}"
            )

        if idx > 0 and start_offset <= prev_offset:
            raise IdxParseError(
                f"Non-increasing byte offset on line {idx + 1}: {start_offset} "
                f"<= previous offset {prev_offset}"
            )

        date_token = parts[2].strip()
        parameter = parts[3].strip()
        level_desc = parts[4].strip()
        forecast_desc = parts[5].strip()
        extra = ":".join(parts[6:]).strip() if len(parts) > 6 else ""

        raw_records.append(
            (
                rec_num,
                start_offset,
                date_token,
                parameter,
                level_desc,
                forecast_desc,
                extra,
                line,
            )
        )
        prev_offset = start_offset

    total_records = len(raw_records)
    records: list[IdxRecord] = []

    for i, (rec_num, start_off, date_tok, param, lvl, fcst, ext, raw) in enumerate(
        raw_records
    ):
        if i + 1 < total_records:
            next_start = raw_records[i + 1][1]
            end_off: int | None = next_start - 1
        else:
            end_off = None

        records.append(
            IdxRecord(
                record_number=rec_num,
                start_offset=start_off,
                end_offset=end_off,
                date_token=date_tok,
                parameter=param,
                level_description=lvl,
                forecast_description=fcst,
                ensemble_description=ext,
                raw_line=raw,
            )
        )

    return records


#: Default canonical variables selected by GFS/GEFS record selectors.
DEFAULT_SELECTION_VARIABLES: tuple[str, ...] = (
    "temperature_2m",
    "precipitation_rate",
    "precipitation_amount_3h",
    "crain",
    "csnow",
    "cfrzr",
    "cicep",
    "relative_humidity_2m",
    "wind_gust",
    "visibility",
    "snow_depth",
    "wind_u_10m",
    "wind_v_10m",
    "cloud_cover_3h",
    "cloud_ceiling",
)


def select_gfs_records(
    records: list[IdxRecord],
    lead_time_hours: int,
    variables: tuple[str, ...] = DEFAULT_SELECTION_VARIABLES,
) -> SelectionResult:
    """Select required GFS GRIB2 records from parsed .idx records.

    GFS Operational Rules:
    * ``temperature_2m``: Matches parameter ``"TMP"`` at level
      ``"2 m above ground"``. At lead 0, matches ``"anl"`` or ``"0 hour fcst"``;
      at lead > 0, matches ``f"{lead_time_hours} hour fcst"``.
    * ``precipitation_rate``: Matches parameter ``"PRATE"`` at level
      ``"surface"``. Strictly matches instantaneous forecast description
      (e.g. ``f"{lead_time_hours} hour fcst"`` or ``"0 hour fcst"`` / ``"anl"``),
      and explicitly rejects time-averaged variants (``"ave fcst"``) or
      accumulated variants (``"acc fcst"``).
    * ``relative_humidity_2m``: Matches parameter ``"RH"`` at level
      ``"2 m above ground"``. At lead 0, matches ``"anl"`` or ``"0 hour fcst"``;
      at lead > 0, matches ``f"{lead_time_hours} hour fcst"``.
    * ``wind_gust``: Matches parameter ``"GUST"`` at level ``"surface"``.
      At lead 0, matches ``"anl"`` or ``"0 hour fcst"``; at lead > 0, matches
      ``f"{lead_time_hours} hour fcst"``.
    * ``visibility``: Matches parameter ``"VIS"`` at level ``"surface"``.
      At lead 0, matches ``"anl"`` or ``"0 hour fcst"``; at lead > 0, matches
      ``f"{lead_time_hours} hour fcst"``.
    * ``snow_depth``: Matches parameter ``"SNOD"`` at level ``"surface"``.
      At lead 0, matches ``"anl"`` or ``"0 hour fcst"``; at lead > 0, matches
      ``f"{lead_time_hours} hour fcst"``.
    * ``wind_u_10m``: Matches parameter ``"UGRD"`` at level
      ``"10 m above ground"``. At lead 0, matches ``"anl"`` or ``"0 hour fcst"``;
      at lead > 0, matches ``f"{lead_time_hours} hour fcst"``.
    * ``wind_v_10m``: Matches parameter ``"VGRD"`` at level
      ``"10 m above ground"``. At lead 0, matches ``"anl"`` or ``"0 hour fcst"``;
      at lead > 0, matches ``f"{lead_time_hours} hour fcst"``.

    Args:
        records: Parsed ``.idx`` records.
        lead_time_hours: Target forecast lead time.
        variables: Canonical platform variable codes to select.

    Returns:
        A :class:`SelectionResult` detailing selected records and any anomalies.
    """
    variable_selections: dict[str, VariableSelection] = {}
    missing_required: list[str] = []
    unsupported: list[str] = []
    ambiguous: list[str] = []
    all_selected: list[IdxRecord] = []

    for var in variables:
        if var == "temperature_2m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "TMP"
                and rec.level_description == "2 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "precipitation_rate":
            matches = [
                rec
                for rec in records
                if rec.parameter == "PRATE"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and "ave fcst" not in rec.forecast_description
                and "acc fcst" not in rec.forecast_description
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "relative_humidity_2m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "RH"
                and rec.level_description == "2 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "wind_gust":
            matches = [
                rec
                for rec in records
                if rec.parameter == "GUST"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "visibility":
            matches = [
                rec
                for rec in records
                if rec.parameter == "VIS"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "snow_depth":
            matches = [
                rec
                for rec in records
                if rec.parameter == "SNOD"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "wind_u_10m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "UGRD"
                and rec.level_description == "10 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "wind_v_10m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "VGRD"
                and rec.level_description == "10 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "precipitation_amount_3h":
            if lead_time_hours == 0:
                # Analysis time has zero accumulation duration; no GRIB record required
                variable_selections[var] = VariableSelection(
                    variable_code=var,
                    status=SelectionStatus.SELECTED,
                    record=None,
                )
            else:
                expected_desc = _expected_apcp_description(lead_time_hours)
                if expected_desc is None:
                    variable_selections[var] = VariableSelection(
                        variable_code=var,
                        status=SelectionStatus.UNSUPPORTED,
                    )
                    unsupported.append(var)
                else:
                    matches = [
                        rec
                        for rec in records
                        if rec.parameter == "APCP"
                        and rec.level_description == "surface"
                        and rec.forecast_description.strip().lower() == expected_desc
                    ]
                    # If multiple identical matches exist (e.g. GFS f003/f006 duplicate lines),
                    # pick the first one (the 6h-resetting family).
                    if len(matches) > 1:
                        matches = [matches[0]]
                    _record_selection(
                        var,
                        matches,
                        variable_selections,
                        all_selected,
                        missing_required,
                        ambiguous,
                    )

        elif var in ("crain", "csnow", "cfrzr", "cicep"):
            if lead_time_hours == 0:
                # Analysis time has no interval-average categorical flags
                variable_selections[var] = VariableSelection(
                    variable_code=var,
                    status=SelectionStatus.SELECTED,
                    record=None,
                )
            else:
                expected_desc = _expected_categorical_description(lead_time_hours)
                param_name = var.upper()
                if expected_desc is None:
                    variable_selections[var] = VariableSelection(
                        variable_code=var,
                        status=SelectionStatus.UNSUPPORTED,
                    )
                    unsupported.append(var)
                else:
                    matches = [
                        rec
                        for rec in records
                        if rec.parameter == param_name
                        and rec.level_description == "surface"
                        and rec.forecast_description.strip().lower() == expected_desc
                    ]
                    if len(matches) > 1:
                        matches = [matches[0]]
                    _record_selection(
                        var,
                        matches,
                        variable_selections,
                        all_selected,
                        missing_required,
                        ambiguous,
                    )

        elif var == "cloud_cover_3h":
            if lead_time_hours == 0:
                # Analysis time has no interval-average cloud cover record
                variable_selections[var] = VariableSelection(
                    variable_code=var,
                    status=SelectionStatus.SELECTED,
                    record=None,
                )
            else:
                expected_desc = _expected_categorical_description(lead_time_hours)
                if expected_desc is None:
                    variable_selections[var] = VariableSelection(
                        variable_code=var,
                        status=SelectionStatus.UNSUPPORTED,
                    )
                    unsupported.append(var)
                else:
                    matches = [
                        rec
                        for rec in records
                        if rec.parameter == "TCDC"
                        and rec.level_description == "entire atmosphere"
                        and rec.forecast_description.strip().lower() == expected_desc
                    ]
                    if len(matches) > 1:
                        matches = [matches[0]]
                    _record_selection(
                        var,
                        matches,
                        variable_selections,
                        all_selected,
                        missing_required,
                        ambiguous,
                    )

        elif var == "cloud_ceiling":
            matches = [
                rec
                for rec in records
                if rec.parameter == "HGT"
                and rec.level_description == "cloud ceiling"
                and _matches_step(rec.forecast_description, lead_time_hours)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        else:
            variable_selections[var] = VariableSelection(
                variable_code=var,
                status=SelectionStatus.UNSUPPORTED,
            )
            unsupported.append(var)

    # Sort selected records strictly by byte offset to preserve upstream GRIB order
    sorted_selected = tuple(sorted(all_selected, key=lambda r: r.start_offset))

    return SelectionResult(
        selected_records=sorted_selected,
        variable_selections=variable_selections,
        missing_required=tuple(missing_required),
        unsupported=tuple(unsupported),
        ambiguous=tuple(ambiguous),
    )


def merge_adjacent_records(
    records: tuple[IdxRecord, ...] | list[IdxRecord],
    *,
    max_gap: int = 0,
) -> tuple[tuple[IdxRecord, ...], ...]:
    """Group sorted IdxRecords into contiguous or near-contiguous spans.

    Two consecutive records r1 and r2 are grouped together if:
    ``r2.start_offset - (r1.end_offset + 1) <= max_gap`` (where r1.end_offset is not None).

    When ``max_gap == 0`` (default), strictly groups only physically adjacent records
    (0-byte gap) with zero extra byte overhead.

    Args:
        records: Sequence of IdxRecord instances, sorted by start_offset.
        max_gap: Maximum allowed gap in bytes between consecutive records to merge.

    Returns:
        A tuple of record groups (each group is a tuple of IdxRecord).
    """
    if not records:
        return ()

    groups: list[list[IdxRecord]] = []
    cur_group: list[IdxRecord] = [records[0]]

    for r in records[1:]:
        prev = cur_group[-1]
        gap = (
            r.start_offset - (prev.end_offset + 1)
            if prev.end_offset is not None
            else 999999999999
        )
        if gap <= max_gap:
            cur_group.append(r)
        else:
            groups.append(cur_group)
            cur_group = [r]

    if cur_group:
        groups.append(cur_group)

    return tuple(tuple(g) for g in groups)


def _record_selection(
    var: str,
    matches: list[IdxRecord],
    variable_selections: dict[str, VariableSelection],
    all_selected: list[IdxRecord],
    missing_required: list[str],
    ambiguous: list[str],
) -> None:
    """Helper to record matches into variable selection and error buckets."""
    if len(matches) == 1:
        rec = matches[0]
        variable_selections[var] = VariableSelection(
            variable_code=var,
            status=SelectionStatus.SELECTED,
            record=rec,
            matched_records=tuple(matches),
        )
        all_selected.append(rec)
    elif len(matches) == 0:
        variable_selections[var] = VariableSelection(
            variable_code=var,
            status=SelectionStatus.REQUIRED_BUT_MISSING,
        )
        missing_required.append(var)
    else:
        variable_selections[var] = VariableSelection(
            variable_code=var,
            status=SelectionStatus.AMBIGUOUS,
            matched_records=tuple(matches),
        )
        ambiguous.append(var)


def select_gefs_records(
    records: list[IdxRecord],
    member: int,
    lead_time_hours: int,
    variables: tuple[str, ...] = DEFAULT_SELECTION_VARIABLES,
) -> SelectionResult:
    """Select required GEFS GRIB2 records from parsed .idx records.

    GEFS Operational Rules:
    * ``temperature_2m``: Matches parameter ``"TMP"`` at level
      ``"2 m above ground"`` and matching ensemble tag (e.g. ``"ENS=+<member>"``).
    * ``precipitation_rate``: GEFS ``pgrb2s`` surface files do not provide
      instantaneous ``prate`` (they provide accumulated ``APCP``). This variable
      is marked :attr:`SelectionStatus.UNSUPPORTED` and does **not** trigger
      missing-required errors or full-file fallback.
    * ``relative_humidity_2m``: Matches parameter ``"RH"`` at level
      ``"2 m above ground"`` and matching ensemble tag.
    * ``wind_gust``: Matches parameter ``"GUST"`` at level ``"surface"``
      and matching ensemble tag.
    * ``visibility``: Matches parameter ``"VIS"`` at level ``"surface"``
      and matching ensemble tag.
    * ``snow_depth``: Matches parameter ``"SNOD"`` at level ``"surface"``
      and matching ensemble tag.

    Args:
        records: Parsed ``.idx`` records.
        member: GEFS perturbation member (1..30) or control member (0).
        lead_time_hours: Target forecast lead time.
        variables: Canonical platform variable codes to select.

    Returns:
        A :class:`SelectionResult` detailing selected records.
    """
    variable_selections: dict[str, VariableSelection] = {}
    missing_required: list[str] = []
    unsupported: list[str] = []
    ambiguous: list[str] = []
    all_selected: list[IdxRecord] = []

    for var in variables:
        if var == "temperature_2m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "TMP"
                and rec.level_description == "2 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "precipitation_rate":
            # GEFS pgrb2s has no instant prate; unsupported by product design
            variable_selections[var] = VariableSelection(
                variable_code=var,
                status=SelectionStatus.UNSUPPORTED,
            )
            unsupported.append(var)

        elif var == "relative_humidity_2m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "RH"
                and rec.level_description == "2 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "wind_gust":
            matches = [
                rec
                for rec in records
                if rec.parameter == "GUST"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "visibility":
            matches = [
                rec
                for rec in records
                if rec.parameter == "VIS"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "snow_depth":
            matches = [
                rec
                for rec in records
                if rec.parameter == "SNOD"
                and rec.level_description == "surface"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "wind_u_10m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "UGRD"
                and rec.level_description == "10 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "wind_v_10m":
            matches = [
                rec
                for rec in records
                if rec.parameter == "VGRD"
                and rec.level_description == "10 m above ground"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        elif var == "precipitation_amount_3h":
            if lead_time_hours == 0:
                variable_selections[var] = VariableSelection(
                    variable_code=var,
                    status=SelectionStatus.SELECTED,
                    record=None,
                )
            else:
                expected_desc = _expected_apcp_description(lead_time_hours)
                if expected_desc is None:
                    variable_selections[var] = VariableSelection(
                        variable_code=var,
                        status=SelectionStatus.UNSUPPORTED,
                    )
                    unsupported.append(var)
                else:
                    matches = [
                        rec
                        for rec in records
                        if rec.parameter == "APCP"
                        and rec.level_description == "surface"
                        and rec.forecast_description.strip().lower() == expected_desc
                        and _matches_gefs_member(rec.ensemble_description, member)
                    ]
                    if len(matches) > 1:
                        matches = [matches[0]]
                    _record_selection(
                        var,
                        matches,
                        variable_selections,
                        all_selected,
                        missing_required,
                        ambiguous,
                    )

        elif var in ("crain", "csnow", "cfrzr", "cicep"):
            if lead_time_hours == 0:
                variable_selections[var] = VariableSelection(
                    variable_code=var,
                    status=SelectionStatus.SELECTED,
                    record=None,
                )
            else:
                expected_desc = _expected_categorical_description(lead_time_hours)
                param_name = var.upper()
                if expected_desc is None:
                    variable_selections[var] = VariableSelection(
                        variable_code=var,
                        status=SelectionStatus.UNSUPPORTED,
                    )
                    unsupported.append(var)
                else:
                    matches = [
                        rec
                        for rec in records
                        if rec.parameter == param_name
                        and rec.level_description == "surface"
                        and rec.forecast_description.strip().lower() == expected_desc
                        and _matches_gefs_member(rec.ensemble_description, member)
                    ]
                    if len(matches) > 1:
                        matches = [matches[0]]
                    _record_selection(
                        var,
                        matches,
                        variable_selections,
                        all_selected,
                        missing_required,
                        ambiguous,
                    )

        elif var == "cloud_cover_3h":
            if lead_time_hours == 0:
                # Analysis time has no interval-average cloud cover record
                variable_selections[var] = VariableSelection(
                    variable_code=var,
                    status=SelectionStatus.SELECTED,
                    record=None,
                )
            else:
                expected_desc = _expected_categorical_description(lead_time_hours)
                if expected_desc is None:
                    variable_selections[var] = VariableSelection(
                        variable_code=var,
                        status=SelectionStatus.UNSUPPORTED,
                    )
                    unsupported.append(var)
                else:
                    matches = [
                        rec
                        for rec in records
                        if rec.parameter == "TCDC"
                        and rec.level_description == "entire atmosphere"
                        and rec.forecast_description.strip().lower() == expected_desc
                        and _matches_gefs_member(rec.ensemble_description, member)
                    ]
                    if len(matches) > 1:
                        matches = [matches[0]]
                    _record_selection(
                        var,
                        matches,
                        variable_selections,
                        all_selected,
                        missing_required,
                        ambiguous,
                    )

        elif var == "cloud_ceiling":
            matches = [
                rec
                for rec in records
                if rec.parameter == "HGT"
                and rec.level_description == "cloud ceiling"
                and _matches_step(rec.forecast_description, lead_time_hours)
                and _matches_gefs_member(rec.ensemble_description, member)
            ]
            _record_selection(
                var,
                matches,
                variable_selections,
                all_selected,
                missing_required,
                ambiguous,
            )

        else:
            variable_selections[var] = VariableSelection(
                variable_code=var,
                status=SelectionStatus.UNSUPPORTED,
            )
            unsupported.append(var)

    sorted_selected = tuple(sorted(all_selected, key=lambda r: r.start_offset))

    return SelectionResult(
        selected_records=sorted_selected,
        variable_selections=variable_selections,
        missing_required=tuple(missing_required),
        unsupported=tuple(unsupported),
        ambiguous=tuple(ambiguous),
    )


def select_records(
    model: str,
    records: list[IdxRecord],
    lead_time_hours: int,
    variables: tuple[str, ...] = DEFAULT_SELECTION_VARIABLES,
    member: int | None = None,
) -> SelectionResult:
    """Dispatch product-aware record selection for a given model.

    Args:
        model: Model identifier (``"gfs"`` or ``"gefs"``).
        records: Parsed ``.idx`` records.
        lead_time_hours: Target forecast lead time.
        variables: Canonical variable codes to select.
        member: GEFS perturbation member identity (required for GEFS).

    Returns:
        A :class:`SelectionResult` detailing selected records.
    """
    if model == "gfs":
        return select_gfs_records(records, lead_time_hours, variables=variables)
    if model == "gefs":
        if member is None:
            raise ValueError("member must be provided for GEFS record selection")
        return select_gefs_records(
            records, member, lead_time_hours, variables=variables
        )
    raise ValueError(f"Unsupported model for selective download: {model!r}")


def _matches_step(desc: str, lead_time_hours: int) -> bool:
    """Check whether a forecast description token matches the target lead."""
    clean = desc.strip().lower()
    if lead_time_hours == 0:
        return clean in ("anl", "0 hour fcst", "0 hour fcst:")
    return clean == f"{lead_time_hours} hour fcst"


def _expected_apcp_description(lead_time_hours: int) -> str | None:
    """Return the expected 6-hour-resetting APCP forecast description string.

    * For leads 3, 9, 15, 21, ... (lead % 6 == 3): "[lead-3]-[lead] hour acc fcst"
    * For leads 6, 12, 18, 24, ... (lead % 6 == 0): "[lead-6]-[lead] hour acc fcst"
    * Non-standard/non-3h leads return None.
    """
    if lead_time_hours <= 0:
        return None
    if lead_time_hours % 6 == 3:
        return f"{lead_time_hours - 3}-{lead_time_hours} hour acc fcst"
    if lead_time_hours % 6 == 0:
        return f"{lead_time_hours - 6}-{lead_time_hours} hour acc fcst"
    return None


def _expected_categorical_description(lead_time_hours: int) -> str | None:
    """Return the expected 6-hour-resetting categorical average forecast description.

    * For leads 3, 9, 15, 21, ... (lead % 6 == 3): "[lead-3]-[lead] hour ave fcst"
    * For leads 6, 12, 18, 24, ... (lead % 6 == 0): "[lead-6]-[lead] hour ave fcst"
    * Non-standard/non-3h leads return None.
    """
    if lead_time_hours <= 0:
        return None
    if lead_time_hours % 6 == 3:
        return f"{lead_time_hours - 3}-{lead_time_hours} hour ave fcst"
    if lead_time_hours % 6 == 0:
        return f"{lead_time_hours - 6}-{lead_time_hours} hour ave fcst"
    return None


def _matches_gefs_member(ens_desc: str, target_member: int) -> bool:
    """Check whether an ensemble token matches the target member number.

    Supports NOMADS conventions:
    * Perturbation members: ``"ENS=+1"``, ``"ENS=+01"``, ``"ENS=+17"``
    * Control member: ``"ENS=0"``, ``"ENS=c00"``, ``"ENS=ctl"``
    """
    clean = ens_desc.strip()
    if not clean:
        # If no ensemble tag is present in the line (e.g. single-member file where
        # perturbation is in directory structure rather than wgrib2 index)
        return True

    # Check ENS=+<member>
    if clean == f"ENS=+{target_member}" or clean == f"ENS=+{target_member:02d}":
        return True

    # Check ENS=<member>
    if clean == f"ENS={target_member}" or clean == f"ENS={target_member:02d}":
        return True

    # Control member variants (member 0)
    if target_member == 0 and clean in ("ENS=0", "ENS=c00", "ENS=ctl"):
        return True

    return False
